name: Selenium Based Scraper

on:
  push:
    branches: [ main ]

jobs:
  scraping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies for python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'
          chromedriver-version: 'latest'
          headless: true

      - name: Print Chrome version (for debugging)
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run scraper
        run: python main.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git add ./data/instamart_product_up.xlsx
          git commit -m "Add scraped Excel data"
          git push

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: main
